@startuml kouka1_1.wsd
actor ユーザ
boundary ブラウザ
control web.php
control Kouka1_1Controller
boundary Kouka1_1indexblade.php
boundary layoutskouka1_1blade.php
boundary componentsmenublade.php
boundary componentsubviewblade.php

ユーザ -> ブラウザ:該当ページをリクエスト[/kouka1_1]
ブラウザ -> web.php: GET[/kouka1_1]
web.php -> Kouka1_1Controller:@index
Kouka1_1Controller->Kouka1_1indexblade.php
Kouka1_1indexblade.php->layoutskouka1_1blade.php:@extend
Kouka1_1indexblade.php<--layoutskouka1_1blade.php
Kouka1_1indexblade.php->componentsmenublade.php:@component
Kouka1_1indexblade.php<--componentsmenublade.php
Kouka1_1indexblade.php->componentsubviewblade.php:@include
Kouka1_1indexblade.php<--componentsubviewblade.php
@enduml