a=int(input('整数a:'))
b=int(input('整数b:'))

print('a+bは', a+b, 'です。')
print('a-bは', a-b, 'です。')
print('a*bは', a*b, 'です。')
print('a/bは', a/b, 'です。')
print('a//bは', a//b, 'です。')
print('a%bは', a%b, 'です。')
print('a**bは', a**b, 'です。')
