a=int(input('整数a:'))
b=int(input('整数b:'))

print('a+bは{}です。'.format(a+b))
print('a-bは{}です。'.format(a-b))
print('a*bは{}です。'.format(a*b))
print('a/bは{}です。'.format(a/b))
print('a//bは{}です。'.format(a//b))
print('a%bは{}です。'.format(a%b))
print('a**bは{}です。'.format(a**b))
